---
- name: This playbook is used to install the packages
  hosts: all
  become: true
  become_method: runas
  become_user: Administrator
  tasks:
 
  - name: Install all Patch
    ansible.windows.win_updates:
      category_names:
        - SecurityUpdates
        - CriticalUpdates
        - UpdateRollups
    become: true
    become_method: runas
    become_user: SYSTEM

  - name: Disable Firewall
    ansible.windows.win_powershell:
      script: |
        Set-MpPreference -DisableRealtimeMonitoring $true
        Set-MpPreference -DisableScriptScanning $true
        Set-MpPreference -DisableBehaviorMonitoring $true
        Set-MpPreference -DisableIOAVProtection $true
        Set-MpPreference -DisableIntrusionPreventionSystem $true
    

  - name: Install SSM Agent
    ansible.windows.win_powershell:
      script: | 
        $dir = $env:TEMP + "\ssm"
        New-Item -ItemType directory -Path $dir -Force
        cd $dir
        (New-Object System.Net.WebClient).DownloadFile("https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/windows_amd64/AmazonSSMAgentSetup.exe", $dir + "\AmazonSSMAgentSetup.exe")
        Start-Process .\AmazonSSMAgentSetup.exe -ArgumentList @("/q", "/log", "install.log") -Wait
        New-Item -ItemType Directory -Path C:\Script
        # https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
        $dlurl = "https://awscli.amazonaws.com/AWSCLIV2.msi"
        $installerPath = Join-Path $env:TEMP (Split-Path $dlurl -Leaf)
        $ProgressPreference = 'SilentlyContinue'
        Invoke-WebRequest $dlurl -OutFile $installerPath
        Start-Process -FilePath msiexec -Args "/i $installerPath /passive" -Verb RunAs -Wait
        Remove-Item $installerPath
        $env:Path += ";C:\Program Files\Amazon\AWSCLIV2"

 
  - name: Pause for 5 minutes to build app cache
    ansible.builtin.pause:
      minutes: 5

  - name: Install firefox
    win_chocolatey:
      name: firefox

  - name: Install Visual c++
    win_chocolatey:
      name: vcredist140

  - name: Reboot a machine that takes time to settle after being booted
    ansible.windows.win_reboot:
      post_reboot_delay: 120
